version: "3.8"
services:
  frontend:
    build:
      context: ./fraunhofer_front
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  backend:
    build:
      context: ./fraunhofer_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

networks:
  default:
    driver: bridge
